### ISSUE TITLE
exception Failure: "get_def: can't find a definition"

### ISSUE THREAD

**Issue by labba** [moflow/moflow#2]
while executing code that i have compiled after a short while getting the following issue:

89.000000Symbolic Run: 91% (15851.959027 eps)
Symbolic Run: Done! (17.756356 seconds)
Fatal error: exception Failure("get_def: can't find a definition")

**Comment by richinseattle** [comment]
This means there are no tainted bytes to track. This usually happens if the incorrect input pattern is supplied. It's also possible an unsupported instruction somehow wipes out your taint tracking in the pintool.

**Comment by richinseattle** [comment]
This is usually caused by unsupported instructions (sse2 optimized libraries such as jpegturbo for example). No workaround other than extending instruction support in the pintool, sorry.
